#!/usr/bin/env bash

set -euo pipefail

sudo pacman -S --needed --noconfirm \
    hyprland \
    waybar \
    rofi \
    mako \
    hyprpaper \
    hyprlock \
    hypridle \
    swayosd \
    grim \
    slurp \
    wl-clipboard \
    brightnessctl \
    playerctl \
    pipewire \
    pipewire-audio \
    pipewire-pulse \
    wireplumber
