#!/usr/bin/env bash

set -euo pipefail

NEOVIM_DIR="$HOME/personal/neovim"
NEOVIM_VERSION="v0.12.5"

sudo pacman -S --needed --noconfirm \
    base-devel \
    cmake \
    ninja \
    gettext \
    curl

mkdir -p "$HOME/personal"

if [[ ! -d "$NEOVIM_DIR/.git" ]]; then
    git clone \
        --branch "$NEOVIM_VERSION" \
        --depth 1 \
        https://github.com/neovim/neovim.git \
        "$NEOVIM_DIR"
else
    git -C "$NEOVIM_DIR" fetch origin "$NEOVIM_VERSION" --depth 1
    git -C "$NEOVIM_DIR" checkout "$NEOVIM_VERSION"
fi

cd "$NEOVIM_DIR"

make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
