#!/usr/bin/env bash

set -euo pipefail

sudo pacman -S --needed --noconfirm \
    zsh \
    zsh-completions \
    git

OH_MY_ZSH="$HOME/.oh-my-zsh"

if [[ ! -d "$OH_MY_ZSH/.git" ]]; then
    git clone \
        --depth 1 \
        https://github.com/ohmyzsh/ohmyzsh.git \
        "$OH_MY_ZSH"
fi

if [[ "$SHELL" != "$(command -v zsh)" ]]; then
    chsh -s "$(command -v zsh)"
fi
