general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/praneeth/Downloads/Wallpapers/vagabond4k.png
    blur_passes = 2
    blur_size = 6
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -60

    outline_thickness = 2

    outer_color = rgb(666666)
    inner_color = rgb(141414)
    font_color = rgb(ffffff)

    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    dots_spacing = 0.3
    dots_center = true
}

label {
    monitor =
    text = $TIME
    font_size = 64
    position = 0, 120
    halign = center
    valign = center
}
