splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/praneeth/Downloads/Wallpapers/vagabond4k.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-2
    path = /home/praneeth/Downloads/Wallpapers/vagabond4k.png
    fit_mode = cover
}
